apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: fsai-os-global-secrets
spec:
  secretTemplates:
    - name: fsai-os-global-secrets
      data:
        DASHBOARD_PASSWORD: ENC[AES256_GCM,data:mJQ6U9JjQBBBdHM4dzTJ39fQCA0d/Ko=,iv:offbmIFZl4Vj64B4OqDjhr3HiqatWZua4soK0FVWL5w=,tag:yg75S/7CL+CMO0knOKME4w==,type:str]
        DATABASE_PASSWORD: ENC[AES256_GCM,data:NxKh2SJ1vPiIS7wKAHzZsgfh4Qkfkg==,iv:4MJZT96Kil5TLeTfhsUisVxj96hnPlmMr8jxaoRuIvQ=,tag:Sphu1puWrQk+9ffxoUjIYg==,type:str]
        DB_NAME: ENC[AES256_GCM,data:jO3GrXKPiYaNhBrBbw==,iv:FKolIhkbAObtiwejF3F+opOnxeAQzFL3AlkOb+DgKXs=,tag:PZJle2R7u1OVLJ79mEpgsg==,type:str]
        DB_PASSWORD: ENC[AES256_GCM,data:Cs1M018+N4AyuRTVbegwdw==,iv:6HcnCAMkZ4/RGi32nWjCpeot5cmMr79RtxuCoDn7puo=,tag:YLciK35j6fUFcT6ENF6tFw==,type:str]
        DB_PORT: ENC[AES256_GCM,data:zyOdfw==,iv:bDo2xRCHhE4r2S/vuLS0oB8sKx9Ujyd5YuMOzxvlRB4=,tag:ympLK6/UnwTtG7emWGz90g==,type:str]
        ENCRYPTION_KEY: ENC[AES256_GCM,data:vwP9W+gzenF+LaCx1eH/pNBwH4vfzzrQslmejfsQCUZi,iv:+zWAXB43f7b5pQoKdCO5U4KUwnpnP9POB6N0qs06mo0=,tag:ZIXeY1AW1T4cHdF4i6i8fQ==,type:str]
        JWT_SECRET: ENC[AES256_GCM,data:3FPsCkzjze7nyLclPLx6rJLsWmyD,iv:n0o8/hWNI7VSEc5b3qpLi/7+Nl4qTsmN6AHG5sdQzCs=,tag:MR/BAwymBBRkxE0iXNx6Gw==,type:str]
        NEXTAUTH_SECRET: ENC[AES256_GCM,data:zJqe15KvIe5grHuShSjBCG3IskWVKdqjmtA=,iv:VJ+9EbBxWLk4TJYOstN2p9lGDb5+KK4vA5ywkEKCMjc=,tag:pY1IL79qwOSlDVQkWqNpCA==,type:str]
        POSTGRES_PASSWORD: ENC[AES256_GCM,data:MnJ1ZTMaRDhD1TN/wcmxYIKrYEVEAQ==,iv:zqC2rzfmtmlsTwXdL0uWRWAJxTnodGoiQHVBuWsNhbY=,tag:NsVKGqy1D5qT8ALEbY17/g==,type:str]
        SALT: ENC[AES256_GCM,data:typoqIak4zyv40TNi6ay,iv:ILlB+bIynjx0FHR16ZdonQxtT92DhI6VLDmixMmtpZg=,tag:AoKi5bVDqiaRjDojBJYaEw==,type:str]
        SECRET_KEY_BASE: ENC[AES256_GCM,data:y22P0yV4NEcOehvEqVPgAZTdQ2Fe/AlyVKw=,iv:u8he+HKu3XVM9Dtqxya8ujmlT4Mh7pqKL7BVUGspuYQ=,tag:TJKS6Q65wzZS0NzSriMfWw==,type:str]
        SERVICE_ROLE_KEY: ENC[AES256_GCM,data:hD0G+TGN1TpWXlhUiV2hsjLs6s2taH3dCTif,iv:Jimp+f/RUVniX3mM3o6KonM/kjhhi0Ff9gGhByFQaFg=,tag:g8BB42x46geL7DDKWpO2/Q==,type:str]
        SMTP_PASS: ENC[AES256_GCM,data:Unlci7aL4hC+y8DAeHJPU2Uy,iv:qa0e8TGBbNY7UTIxPrbENs5kp84fhMuZ7vpvAQBVtA8=,tag:c6SXJkhxKtxWwH82cL+u9g==,type:str]
        SUPABASE_ANON_KEY: ENC[AES256_GCM,data:9H2IH7X7xZO8MMJNUIOuvc7WPVgKMGX1o2f7Cg==,iv:rmqAbt34MCOB45SeL7J+KuGyTZ6gQ+EjnX25e6LcBwc=,tag:jh292FBKp9kXNbbXA9/SoA==,type:str]
        SUPABASE_DB_URL: ENC[AES256_GCM,data:iU22rx2th99HGAvUX6HQT2zdh1PLTzoNV2Km5VEozGt+4TdHqofVPTh7ztaYeKWZCKSMP5ubI9epKqMDsQg48kd1Uojkh6F7H8AVlsNoTsTmJM+6mniFhVquUX5DI0VVBJOO/D608olC,iv:UfKh60bwXnfV9UAeuOXMnjmlDm7rEi8Taks1m0Fql6M=,tag:sOC1GZFc+mVYmr/w+fUuCw==,type:str]
        SUPABASE_SERVICE_ROLE_KEY: ENC[AES256_GCM,data:gSJJD/1mEh+/zeHjhxZUe8k/0FFbMBBnggUMv+q0ziD/8BUs,iv:aKC/PNJfVEStM3zOoaBnh2PaEoU92TWIAmIfNPr/TTo=,tag:Zsj6pIIkOToc1YlqnkmVlA==,type:str]
        S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:D60arRpIqAdSfeooXMqNJjuRvboF,iv:N2YqY8mA3RA0QHmfm+Y+KXsl0vgSWo6bnwDTutBl/1Y=,tag:rUpJnvki5GfyUh4tTleX9w==,type:str]
        S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:OXMXWPqxrEpcXLvVOe485jLmy9ZP,iv:VCFogj5oIW32m8rMLjP0LDjT3oBjtFl8Hlv31nMYmys=,tag:RkncqBVNfqi4uGSn/bNSXA==,type:str]
        S3_STORAGE_ACCESS_KEY_ID: ENC[AES256_GCM,data:tq1A8aL+WM7QCqY5Ty4sejdXDA2Erh8=,iv:Q8m8G3ViQ2WlbVwx9bSaFJv/kmmmULEK0rBZJRd6qmk=,tag:M97o84yHVU+5ovqhUoh43g==,type:str]
        S3_STORAGE_ACCESS_KEY_SECRET: ENC[AES256_GCM,data:hEipHdrZEszhD4j+V8Z0LWPREITMX6c=,iv:qrDBS2mLfhmVaLkXUJ+MXewiTn9CDXl6ahQE5ox1spU=,tag:jw6Y60H+Z2hxiLDUD9LgUA==,type:str]
sops:
  age:
    - recipient: age1a75gcewnqrplsckw23c5pvzsuy7xs5a9uuhqn6kshlr98yvq0sas8kclma
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSM2pYUGZXWWVpSGJ5Wnlz
        eTFpS2NiVk94bHhSKzNzNEIvK3l3ellEczNJClZFZnp0aWlBc0hqbGxOS2ZyNDBY
        bkpHdVlvUEp3ZTJkbzNXelNHZ2IraTAKLS0tIHhEMUhnaGFrUTB2M3dUTDNqVis4
        UUl3NjFxUkZkNE4yVkN6YVZCT1Npc3MKl6pZ6Y5XZ8wK+61rC/RqdzN9+zeGyotH
        jN3CS5WjQZlyXB0Ub+F6c8CSBCWIjWQE3yA9pIsUMikWRj34C9Rj5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-29T04:53:51Z"
  mac: ENC[AES256_GCM,data:DIqBpwvokAs1oD2sO+6f93rsPh84plRD5NUQo9Yge8xM/nkx3PNHg1KCFlYzts1nKlBeCt5UM+E9UYe7WMRGFF6s9VPs/JgNE2Su3GuMxpzJ3pCwvISEVLCljvdWGlK4yW+giBszeGqrKYgMA/KhYE+UmKimn2M+4XmTmMkrHLQ=,iv:24Aem6LWQMuqO7dnrMsvnHwshW0honldGH9iPlHoACs=,tag:QNa64YefQoXcooYKsV/z2w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
