apiVersion: v1
kind: Secret
metadata:
  name: fsai-os-global-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
